const LANG_zh_CN = {
  "feeling luckly": "随机",
  files: "文件",
  folders: "文件夹",
  manage: "管理",
  "manage user": "用户管理",
  active: "激活",
  "search files": "搜索文件",
  "search folders": "搜索文件夹",
  "enter filename": "输入文件名",
  "enter folder name": "输入文件名",
  search: "搜索",
  "last page": "上一页",
  all: "全部",
  "loading...": "加载中...",
  "next page": "下一页",
  "search polders": "搜索文件夹",
  "share with others!": "分享给好友！",
  "click the filename below to enjoy music!": "点击下面的文件名开始享受音乐！",
  "share link": "分享链接",
  hi: "您好",
  profile: "个人信息",
  "user profile": "用户信息",
  "save username": "更改用户名",
  save: "保存",
  reset: "重置",
  "old password": "旧密码",
  "new password": "新密码",
  "confirm new password": "确认新密码",
  "change password": "更改密码",
  reviews: "评论",
  review: "评论",
  on: "在",
  edit: "编辑",
  "modified on": "修改于",
  share: "分享",
  delete: "删除",
  remove: "移除",
  "file details": "文件详情",
  download: "下载",
  logout: "登出",
  tags: "标签",
  "add tag": "添加标签",
  "select a tag": "选择一个标签",
  "review page": "评论页面",
  submit: "提交",
  users: "用户",
  feedbacks: "反馈",
  feedback: "反馈",
  date: "时间",
  action: "操作",
  "new tag name": "新标签名",
  "new tag description": "新标签描述",
  "update database": "更新索引",
  "updating...": "更新中...",
  refresh: "刷新",
  filename: "文件名",
  "folder name": "文件夹名",
  size: "大小",
  "player status": "播放状态",
  play: "播放",
  stop: "停止",
  "stop timer": "定时停止",
  loop: "循环",
  raw: "无损",
  prepare: "预转码",
  "file size": "文件大小",
  login: "登陆",
  register: "注册",
  "play: play using browser player.": "播放: 使用浏览器播放",
  "info for more actions.": "详细: 查看更多相关信息",
  info: "详细",
  close: "关闭",
  "please enter username and password": "请输入用户名和密码",
  username: "用户名",
  password: "密码",
  "please fill out all fields": "请完整填写所有信息",
  "password do not match": "两次密码不一致",
  "password updated successfully!": "密码已成功更新！",
  role: "身份",
  user: "用户",
  admin: "管理员",
  anonymous: "匿名",
  "select a role": "选择身份",
  "walk path": "遍历目录",
  "pattern wav flac mp3": "拓展名 wav flac mp3",
  "review updated": "已修改评论",
  "review deleted": "已删除评论",
  "edit review": "编辑评论",
  view: "查看",
  "tag updated successfully": "标签修改成功",
  "tag deleted successfully": "标签删除成功",
  "edit tag": "编辑标签",
  id: "编号",
  "created by": "创建者",
  "create tag": "创建新标签",
  name: "名称",
  description: "描述",
  "are you sure you want to delete this file?": "你确定要删除这个文件吗？",
  "filename updated": "已修改文件名",
  "please select a tag": "请选择一个标签",
  "files in folder": "文件夹内",
  "preparing...": "转码中...",
  "view source code on github": "在 Github 上查看源代码",
};

export default LANG_zh_CN;
